apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: learn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 200M